ftp:
  host: ${PHC_FTP_HOST}
  user: ${PHC_FTP_USER}
  password: ${PHC_FTP_PASSWORD}
  path: ${PHC_FTP_PATH}

jaeger:
  host: ${PHC_JAEGER_HOST}
  port: ${PHC_JAEGER_PORT}
  service_name: ${PHC_JAEGER_NAME}